export const quickFilter = [
    `3 Star`,
    `Buffet`,
    `Chinese`,
    `Dineout Pay`,
    `Happy Hours`,
    `Italian`,
    `North Indian`,
    ` Pure Veg`,
];

export const cuisniesFilter = [
    `American`,
    `Bengali`,
    `Cantonese`,
    `European`,
    `Greek`,
    `Beverages`,
    `Chettinad`,
    `Gujarati`,
    `Japanese`,
    `Malaysian`,
    `Moroccan`,
    `Arabian`,
    `Bihari`,
    `Chinese`,
    `Finger Food`,
    `Health Food`,
    `Kashmiri`,
    `Mangalorean`,
    `Mughlai`,
    `Asian`,
    `Biryani`,
    `Continental`,
    `French`,
    `Hyderabadi`,
    `Kerala`,
    `Mediterranean`,
    `Naga`,
    `Assamese`,
    `Burger`,
    `Desserts`,
    `Fusion`,
    `Indonesian`,
    `Korean`,
    `Mexican`,
    `Nepalese`,
    `Awadhi`,
    `Burmese`,
    `Ethiopian`,
    `Goan`,
    `Iranian`,
    `Lebanese`,
    `North Eastern`,
];

export const tagsFilter = [
    `1 plus 1 on Food and Drinks`,
    `Barbeque Nation Super Savers`,
    `Best Buffet`,
    `5 Star`,
    `Bars`,
    `Best Buffets`,
    `Andaz Delhi`,
    `Best All Day Dining`,
    `Best Buffets and Thaalis`,
    `BBQ Special`,
    `Best Bars`,
    `Best Burgers`,
    `Bakery`,
    `Best Bars and Pubs`,
    `Best Cafes`,
    `Bar`,
    `Best Budget Friendly Restaurants`,
    `Best Cafes to Chill`,
];


export const sortData = [
    "Ratings",
    "Price High to Low",
    "Price Low to High"
];

export const locationNames = [
    { label: "Chennai", year: 1994 },
    { label: "Mumbai", year: 1972 },
    { label: "Delhi", year: 1472 },
];